Vagrant.configure("2") do |config|
	config.vm.provider "hyperv"

	config.vm.provider "hyperv" do |v|
		v.memory = 512
	end
	#config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "dbserver" do |db|
    db.vm.box = "bento/ubuntu-16.04"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
  end
  
  config.vm.define "appserver" do |app|
    app.vm.box = "bento/ubuntu-16.04"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
  end
end